stages:
- stage: Compilacion
  displayName: Se compila
  jobs:
  - template: ../helpers/compilacion.yaml
- stage: Mensaje
  jobs:
  - job: mensaje
    pool:
      vmImage: ubuntu-latest
    steps:
      script: echo "hola solo para prueba"
