stages:
- stage: Mensaje
  jobs:
  - job: mensaje
    pool:
      vmImage: ubuntu-latest
    steps:
      - script:  echo "hola solo para prueba"
- stage: Compilacion
  dependsOn: Mensaje
  displayName: Se compila
  jobs:
    ${{ if contains(variables['Build.SourceVersionMenssage'], 'compila') }}:
    - template: ../helpers/compilacion.yaml
    ${{ else }}
      jobs:
        steps:
          - script:  echo "no hay nada que compilar"
    

