stages:
- stage: Mensaje
  jobs:
  - job: mensaje
    pool:
      vmImage: ubuntu-latest
    steps:
      - script:  echo "hola solo para prueba"
- stage: Compilacion
  dependsOn: Mensaje
  displayName: Se compila
  jobs:
  - template: ../helpers/compilacion.yaml

